#!/usr/bin/env python

import requests
import sys

host=(sys.argv[1])
#host="135.250.193.220"
port="28443"

URL="https://%s:%s/oss/sure/equipments" %(host, port)

#print URL

headers = {'content-type': 'application/xml', 'Accept': 'application/json', 'appId': 'SURE_APP', 'tenantId':'T0', 'ugId':'Admin_UserGroup', 'Authorization':'Basic YWRtaW46YWRtaW5AMTIz'}

payload='/root/python/payload/postequipment.xml'

res=requests.post(url=URL, headers=headers, data=open(payload), verify=False)

#print (res.json)

output=(res.status_code)

#print output
